url: https://yuting_website.github.io
baseurl: 

# Site settings
title: Hello, I'm Yuting Weng
email: jessicaweng91717@gmail.com
description: "Hello, Welcome to Yuting Weng's Personal Website!"


# Team names, titles and social links
people:
- pic: 1
  position: Chicago, IL, USA
  social:
    - title: gmail
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:jessicaweng91717@gmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/yuting17/
  - title: github
    url: https://github.com/Yu-TingWeng?tab=repositories

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# Additional page settings
pages:
  - title: Portfolio
    permalink: /portfolio/